### ISSUE TITLE
Timeline does not order time points numerically or according to factor levels

### ISSUE THREAD

**Issue by mattwarkentin** [JohnCoene/echarts4r#257]
Hi @JohnCoene,

Maybe I'm doing something wrong but the `timeline` feature doesn't seem to order the timepoints in a numeric manner or by enforcing the factor levels.
```r
library(echarts4r)
library(tidyverse)

enframe(rnorm(10*30), NULL, "x") %>% 
  mutate(time = rep(1:10, 30)) %>% 
  group_by(time) %>% 
  e_charts(time, timeline = TRUE) %>% 
  e_histogram(x)
```
Timeline will be ordered 1, 10, 2, 3, etc.

When you factor, the order is still incorrect and it also breaks the chart in an odd way...
```r
enframe(rnorm(10*30), NULL, "x") %>% 
  mutate(time = factor(rep(1:10, 30), levels = 1:10)) %>% 
  group_by(time) %>% 
  e_charts(time, timeline = TRUE) %>% 
  e_histogram(x)
```

**Comment by JohnCoene** [comment]
To the best of my understanding it does order by factor or numeric.

In both your examples the order of the time steps expected is 1 through 10. The example below five 10 through 1. 

```r
tibble::enframe(rnorm(10*30), NULL, "x") %>% 
  dplyr::mutate(time = factor(rep(1:10, 30), levels = rev(1:10))) %>% 
  group_by(time) %>% 
  e_charts(time, timeline = TRUE) %>% 
  e_histogram(x)
```

Am I missing something?

**Comment by mattwarkentin** [comment]
I think your example code doesn't work right either...at least not for me...
```r
library(tidyverse)
library(echarts4r)
tibble::enframe(rnorm(10*30), NULL, "x") %>% 
  dplyr::mutate(time = factor(rep(1:10, 30), levels = rev(1:10))) %>% 
  group_by(time) %>% 
  e_charts(time, timeline = TRUE) %>% 
  e_histogram(x)
```
<img width="621" alt="Screen Shot 2021-01-02 at 6 13 19 PM" src="https://user-images.githubusercontent.com/27825069/103468348-36e4ea80-4d26-11eb-8b05-6f11a14b69af.png">

**Comment by JohnCoene** [comment]
Sorry it might have been something I fixed recently. Can you reinstall the GitHub version and let me know?

**Comment by mattwarkentin** [comment]
The timeline data isn't sorted properly, and the histogram for each point in the timeline is incorrect, also...

**Comment by mattwarkentin** [comment]
> Sorry it might have been something I fixed recently. Can you reinstall the GitHub version and let me know?

Sure, let me try it now...will report back

**Comment by mattwarkentin** [comment]
Okay, the dev version fixed the timeline sorting issue, but the x-axis is still wrong. The domain of x should roughly be between -2 and 2, since it is just `N(0, 1)`, but the x-axis is 1-10 also.
```r
library(tidyverse)
library(echarts4r)
tibble::enframe(rnorm(10*30), NULL, "x") %>% 
  dplyr::mutate(time = factor(rep(1:10, 30), levels = 1:10)) %>% 
  group_by(time) %>% 
  e_charts(time, timeline = TRUE) %>% 
  e_histogram(x)
```
<img width="621" alt="Screen Shot 2021-01-02 at 6 19 12 PM" src="https://user-images.githubusercontent.com/27825069/103468451-094c7100-4d27-11eb-824c-042b6af08c42.png">

**Comment by mattwarkentin** [comment]
``` r
library(tidyverse)
library(echarts4r)

dd <- 
  tibble::enframe(rnorm(10*30), NULL, "x") %>% 
  dplyr::mutate(time = factor(rep(1:10, 30), levels = 1:10)) %>% 
  group_by(time)

dd %>% 
  e_charts(time, timeline = TRUE) %>% 
  e_histogram(x)

dd %>% 
  ggplot(aes(x, fill = time)) +
  geom_histogram()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```
<img width="621" alt="Screen Shot 2021-01-02 at 6 22 03 PM" src="https://user-images.githubusercontent.com/27825069/103468494-8841a980-4d27-11eb-898a-51907bcd4fd8.png">
<img width="621" alt="Screen Shot 2021-01-02 at 6 22 11 PM" src="https://user-images.githubusercontent.com/27825069/103468497-8a0b6d00-4d27-11eb-8b8a-085acc6809bc.png">

**Comment by JohnCoene** [comment]
I'm not behind my computer right so cannot check. What is the expected output here exactly? You are using the `time` variable both for the timeline and on the `x` axis? I think that if used on the `group_by` (and thus timeline) it should not be used on the `x` axis.

**Comment by mattwarkentin** [comment]
Okay, you nailed it. It was not necessary to specify `time` in `e_charts()` when the `tibble` is grouped by the time line variable. My mistake. It works as expected with the following code:
```r
enframe(rnorm(10*30), NULL, "x") %>% 
    mutate(time = factor(rep(1:10, 30), levels = 1:10)) %>% 
    group_by(time) %>% 
    e_charts(timeline = TRUE) %>% 
    e_histogram(x)
```

**Comment by mattwarkentin** [comment]
Sorry! I'm new to `echarts` :(

**Comment by JohnCoene** [comment]
No, no, don't apologize, really! :)
