### ISSUE TITLE
echarts4rBox does not display bars when ran in Docker image

### ISSUE THREAD

**Issue by domsle** [JohnCoene/echarts4r#293]
Hello,

I am having a problem with a shiny dashboard that includes echarts4rBox. In case of a dashboard running in RStudio I have a box that looks like follows (please excuse me for the grey overlay):
![image](https://user-images.githubusercontent.com/18559095/111796494-83bd7380-88c8-11eb-90f8-7673378d7d72.png)
However, the same box, using exacly the same code, but in docker image does not show bars (or whole chart?):
![image](https://user-images.githubusercontent.com/18559095/111796795-d1d27700-88c8-11eb-88c3-9fff589b80c3.png)
 
The data used for this box looks as follows:
```
   group_position     n
            <int> <int>
 1              1     7
 2              2     9
 3              3     6
 4              4     7
 5              5     8
 6              6     5
 7              7     7
 8              8     8
 9              9     5
10             10     3
```
So it can be mimicked with a call like `organic_positions <- data.frame(group_position = 1:10, n = 20:11)`.

Code for creating the box is as follows (I doubt that additional options have any impact here, but to be sure I am not simplifying the code):
```
echarts4rBox(organic_positions,
                         x = group_position,
                         y = n,
                         type = 'bar',
                         text = 'Organic Count:',
                         subtext = '146',
                         # text_color = 
                         color = '#ffffff',
                         background_color = '#006d77',
                         text_color = '#ffffff',
                         title_args = list(textStyle = list(fontSize =19,
                                                            fontWeight = 'lighter',
                                                            textBorderColor = '#222222',
                                                            textBorderWidth = 1),
                                           subtextStyle = list(fontSize = 29,
                                                               fontWeight = 'normal',
                                                               color = '#ffffff',
                                                               textBorderColor = '#222222',
                                                               textBorderWidth = 1))
            )
```

My first guess is that the docker image I have created is missing some libraries - so here are the libraries I have installed on top of regular `rocker/r-ver:4.0.2` image:
```
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libglpk-dev
```
Is there a possibility that it is caused by missing a system library? 

I did not notice any errors in the Chrome console, only these warnings, that don't seem related:
![image](https://user-images.githubusercontent.com/18559095/111800015-d3516e80-88cb-11eb-85bb-87ff645edaee.png)

Additionally sessionInfo on the docker outputs this:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-openmp/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] readr_1.4.0           stringi_1.5.3         jsonlite_1.7.2       
 [4] purrr_0.3.4           tibble_3.1.0          tidyr_1.1.3          
 [7] httr_1.4.2            shinydashboard_0.7.1  highcharter_0.8.2    
[10] echarts4r_0.4.0       DT_0.17               dplyr_1.0.5          
[13] shinycssloaders_1.0.0 shinyWidgets_0.6.0    shiny_1.6.0          

loaded via a namespace (and not attached):
 [1] zoo_1.8-9         tidyselect_1.1.0  bslib_0.2.4       lattice_0.20-41  
 [5] vctrs_0.3.6       generics_0.1.0    htmltools_0.5.1.1 yaml_2.2.1       
 [9] utf8_1.2.1        rlang_0.4.10      jquerylib_0.1.3   later_1.1.0.1    
[13] pillar_1.5.1      glue_1.4.2        withr_2.4.1       TTR_0.24.2       
[17] lifecycle_1.0.0   quantmod_0.4.18   stringr_1.4.0     htmlwidgets_1.5.3
[21] fastmap_1.1.0     httpuv_1.5.5      crosstalk_1.1.1   curl_4.3         
[25] fansi_0.4.2       broom_0.7.5       xts_0.12.1        Rcpp_1.0.6       
[29] xtable_1.8-4      promises_1.2.0.1  backports_1.2.1   cachem_1.0.4     
[33] mime_0.10         fs_1.5.0          hms_1.0.0         digest_0.6.27    
[37] rlist_0.4.6.1     grid_4.0.2        tools_4.0.2       magrittr_2.0.1   
[41] sass_0.3.1        crayon_1.4.1      pkgconfig_2.0.3   ellipsis_0.3.1   
[45] data.table_1.14.0 lubridate_1.7.10  assertthat_0.2.1  R6_2.5.0         
[49] igraph_1.2.6      compiler_4.0.2  
```

While the Rstudio system shows:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-openmp/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] readr_1.4.0           highcharter_0.8.2     echarts4r_0.4.0       shinydashboard_0.7.1 
 [5] stringi_1.5.3         jsonlite_1.7.2        purrr_0.3.4           tibble_3.1.0         
 [9] tidyr_1.1.3           httr_1.4.2            DT_0.17               dplyr_1.0.5          
[13] shinycssloaders_1.0.0 shinyWidgets_0.5.7    shiny_1.6.0          

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        lubridate_1.7.10  lattice_0.20-41   zoo_1.8-9         assertthat_0.2.1 
 [6] digest_0.6.27     packrat_0.5.0     utf8_1.1.4        mime_0.10         R6_2.5.0         
[11] backports_1.2.1   evaluate_0.14     pillar_1.5.1      rlang_0.4.10      curl_4.3         
[16] rstudioapi_0.13   data.table_1.14.0 jquerylib_0.1.3   TTR_0.24.2        rmarkdown_2.7    
[21] urltools_1.7.3    stringr_1.4.0     htmlwidgets_1.5.3 igraph_1.2.6      triebeard_0.3.0  
[26] tinytex_0.30      broom_0.7.5       compiler_4.0.2    httpuv_1.5.5      xfun_0.21        
[31] pkgconfig_2.0.3   htmltools_0.5.1.1 tidyselect_1.1.0  fansi_0.4.2       withr_2.4.1      
[36] crayon_1.4.1      later_1.1.0.1     grid_4.0.2        xtable_1.8-4      lifecycle_1.0.0  
[41] DBI_1.1.1         magrittr_2.0.1    rlist_0.4.6.1     quantmod_0.4.18   cli_2.3.1        
[46] debugme_1.1.0     cachem_1.0.4      renv_0.13.0       fs_1.5.0          promises_1.2.0.1 
[51] bslib_0.2.4       ellipsis_0.3.1    xts_0.12.1        generics_0.1.0    vctrs_0.3.6      
[56] tools_4.0.2       glue_1.4.2        hms_1.0.0         crosstalk_1.1.1   fastmap_1.1.0    
[61] yaml_2.2.1        knitr_1.31        sass_0.3.1  
```

I hope this information is helpful, in case anything else is needed I will post it.

**Comment by JohnCoene** [comment]
Strange indeed, could you share the dockerfile with me?

**Comment by JohnCoene** [comment]
I don't think it's the Linux dependencies, if that was the case the package would not even install and `docker build` would fail. You can find the dependencies I use for travis [here](https://github.com/JohnCoene/echarts4r/blob/master/.travis.yml)

**Comment by domsle** [comment]
Thanks for quick reply!

Dockerfile:
```
FROM rocker/r-ver:4.0.2

    RUN apt-get update
    RUN apt-get install -y libcurl4-openssl-dev
    RUN apt-get install -y libssl-dev
    RUN apt-get install -y zlib1g-dev
    RUN apt-get install -y libxml2-dev
    RUN apt-get install -y libglpk-dev
    
    
RUN R -e "install.packages('remotes')"
RUN R -e "remotes::install_version('dplyr')"
RUN R -e "remotes::install_version('tidyr')"
RUN R -e "remotes::install_version('httr')"
RUN R -e "remotes::install_version('purrr')"
RUN R -e "remotes::install_version('lubridate')"
RUN R -e "remotes::install_version('shiny')"
RUN R -e "remotes::install_version('shinyWidgets')"
RUN R -e "remotes::install_version('DT')"
RUN R -e "remotes::install_version('jsonlite')"
RUN R -e "remotes::install_version('stringi')"
RUN R -e "remotes::install_version('urltools')"
RUN R -e "remotes::install_version('shinycssloaders')"
RUN R -e "remotes::install_version('echarts4r')"
RUN R -e "remotes::install_version('igraph')"
RUN R -e "remotes::install_version('highcharter')"
RUN R -e "remotes::install_version('shinydashboard')"
RUN R -e "remotes::install_version('readr')"
    


    RUN mkdir /root/app
      COPY . /root/app
      
      EXPOSE 3838
    CMD ["R", "-e", "shiny::runApp('/root/app', port = 3838, host = '0.0.0.0')"]
    
```

**Comment by domsle** [comment]
After adding a line with these dependancies: `RUN apt-get install -y libjq-dev libprotobuf-dev protobuf-compiler libprotobuf-dev libprotoc-dev libudunits2-dev libv8-dev`, the chart is still missing.

**Comment by JohnCoene** [comment]
I'm not sure what `install_version` does exactly when not specified a version. Replacing with `install_github("JohnCoene/echarst4r")` works for me (tested the dockerfile below).

```dockerfile
FROM rocker/r-ver:4.0.2

RUN apt-get update
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libglpk-dev

RUN R -e "install.packages('remotes')"
RUN R -e "remotes::install_version('shiny')"
RUN R -e "remotes::install_github('JohnCoene/echarts4r')"

RUN mkdir /root/app
COPY . /root/app
   
EXPOSE 3838
CMD ["R", "-e", "shiny::runApp('/root/app', port = 3838, host = '0.0.0.0')"]
```

**Comment by domsle** [comment]
From my experience not specifing the version results in the latest version. I use it this way, because remotes seems to me more reliable for specific versions then plain `install.packages`, while not having as many dependancies as `devtools` has. It is also easier to just add specific version later.

Anyway, after changing this line to:
`RUN R -e "remotes::install_github('JohnCoene/echarts4r')"` it still has the same issue.

**Comment by JohnCoene** [comment]
Docker should not interfere with this, particularly the front-end.

I pushed my example [here](https://github.com/JohnCoene/echarts4r-docker-test)

**Comment by domsle** [comment]
Well, now I am really confused. I tried your example app, and it works. I also added your boxes to the app and again, in RStudio:
![image](https://user-images.githubusercontent.com/18559095/111811082-f9304080-88d6-11eb-895b-abaec2590069.png)

While in Docker my boxes are still broken:
![image](https://user-images.githubusercontent.com/18559095/111811183-15cc7880-88d7-11eb-8a97-013b5b4b1267.png)

**Comment by JohnCoene** [comment]
I'm sorry, I really can't debug that given what I have at hand. Did you try replacing `install_version` by `install_github` by any chance?

**Comment by domsle** [comment]
Thanks for your help!

I have already replaced install_version with install_github:

> 
> Anyway, after changing this line to:
> `RUN R -e "remotes::install_github('JohnCoene/echarts4r')"` it still has the same issue.

It appears I have found the problem. As it turns out, valueBoxes did not work when they were using data written in tibbles. After changing data to data.frame using `as.data.frame()` everything works perfectly. 

A dput of tibble that does not work:
```
structure(list(value = c(26.2, 50.4, 74.6, 98.9, 268, 317, 414, 
487), n = c(3L, 3L, 6L, 1L, 1L, 1L, 1L, 1L)), row.names = c(NA, 
-8L), class = c("tbl_df", "tbl", "data.frame"))
```
When using this tibble, I don't get a working valueBox, but after adding a `as.data.frame()`, it starts to work. 

Again, thank for your help. In case you would like any more data from me, to be able to debug this one, I am happy to help. In other case, I am closing this one.

Wish you all the best, and stay healthy :)
